site_name: Acervo de Estudos
site_url: https://mateusaledev.github.io/
theme:
  name: material
  language: pt
  features:
    - navigation.top
    - navigation.expand
    - navigation.indexes
    - search.highlight
    - search.share
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true

nav:
  - Início: index.md
  - Documentação:
      - Visão Geral: acervo.md
      - Backend:
          - Introdução: backend/index.md
          - APIs: backend/apis.md
      - Frontend:
          - Introdução: frontend/index.md
          - React: frontend/react.md
      - DevOps:
          - Introdução: devops/index.md
