site_name: Acervo de Estudos
site_url: https://mateusaledev.github.io/
repo_url: https://github.com/mateusaledev/mateusaledev.github.io
repo_name: mateusaledev/docs

theme:
  name: material
  language: pt
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: JetBrains Mono
    code: JetBrains Mono
  features:
    - navigation.top
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - header.autohide
  icon:
    repo: fontawesome/brands/github
    logo: material/library
  favicon: assets/favicon.png
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - footnotes
  - codehilite
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - tags

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mateusaledev
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/mateusaledev

nav:
  - Início: index.md
  - Backend:
      - Introdução: backend/index.md
      - APIs: backend/apis.md
  - Frontend:
      - Introdução: frontend/index.md
      - React: frontend/react.md
  - DevOps: devops/index.md
